enumPropertyNaming: UPPERCASE
library: jvm-retrofit2
packageName: com.usewalletkit.sdk.generated
parcelizeModels: true
useCoroutines: true
apiDocs: false
modelDocs: false
apiTests: false
modelTests: false
