/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.usewalletkit.sdk.openapi.models

import com.usewalletkit.sdk.openapi.models.Network

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass
import android.os.Parcelable
import kotlinx.parcelize.Parcelize

/**
 * 
 *
 * @param transactionHash 
 * @param network 
 * @param status 
 * @param contractAddress If the transaction is a contract creation, this field will be populated with the contract address.
 */
@Parcelize


data class GetTransactionStatusByHashResponse (

    @Json(name = "transaction_hash")
    val transactionHash: kotlin.String,

    @Json(name = "network")
    val network: Network,

    @Json(name = "status")
    val status: kotlin.String,

    /* If the transaction is a contract creation, this field will be populated with the contract address. */
    @Json(name = "contract_address")
    val contractAddress: kotlin.String? = null

) : Parcelable

