/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.usewalletkit.sdk.openapi.models


import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass
import android.os.Parcelable
import kotlinx.parcelize.Parcelize

/**
 * 
 *
 * @param userId 
 * @param verificationCode 
 */
@Parcelize


data class UsersVerifyLoginRequest (

    @Json(name = "user_id")
    val userId: kotlin.String,

    @Json(name = "verification_code")
    val verificationCode: kotlin.String

) : Parcelable

