/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package com.usewalletkit.sdk.openapi.models

import com.usewalletkit.sdk.openapi.models.Network

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass
import android.os.Parcelable
import kotlinx.parcelize.Parcelize

/**
 * 
 *
 * @param id 
 * @param createdAt 
 * @param network 
 * @param address 
 * @param name 
 * @param ownerId 
 */
@Parcelize


data class Wallet (

    @Json(name = "id")
    val id: kotlin.String,

    @Json(name = "created_at")
    val createdAt: kotlin.String,

    @Json(name = "network")
    val network: Network,

    @Json(name = "address")
    val address: kotlin.String,

    @Json(name = "name")
    val name: kotlin.String? = null,

    @Json(name = "owner_id")
    val ownerId: kotlin.String? = null

) : Parcelable

